# Generated by Django 2.2.16 on 2020-09-17 08:03

from django.db import migrations, models


def create_group_data_owner(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    permissions = Permission.objects.filter(
        codename__in=(
            'view_countrydailystatus',
            'view_countryweeklystatus',
            'view_realtimeconnectivity',
            'view_schooldailystatus',
            'view_schoolweeklystatus',
            'view_country',
            'view_school',

            'add_fileimport',
            'change_fileimport',
            'delete_fileimport',
            'view_fileimport'
        )
    )

    group = Group.objects.create(
        name='Data Owner',
    )
    group.permissions.set(permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('custom_auth', '0006_applicationuser_countries_available'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.RunPython(create_group_data_owner, migrations.RunPython.noop),
    ]
