# Generated by Django 2.2.16 on 2020-09-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0020_auto_20200923_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_speed',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Down speed (bps)'),
        ),
    ]
