# Generated by Django 2.2.16 on 2020-10-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0028_auto_20201012_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryweeklystatus',
            name='date_of_data_exist',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
