# Generated by Django 2.2.16 on 2020-10-16 10:49

from django.db import migrations


def set_date_of_data_exists(apps, schema_editor):
    Country = apps.get_model('locations', 'Country')
    CountryWeeklyStatus = apps.get_model('connection_statistics', 'CountryWeeklyStatus')

    for country in Country.objects.all():
        weekly_statuses = CountryWeeklyStatus.objects.filter(country=country, integration_status__in=[1, 2, 3])
        if weekly_statuses.exists():
            date = weekly_statuses.first().date
            CountryWeeklyStatus.objects.filter(
                country=country, integration_status__in=[1, 2, 3]
            ).update(date_of_data_exist=date)


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0029_countryweeklystatus_date_of_data_exist'),
        ('locations', '0006_country_date_of_join'),
    ]

    operations = [
        migrations.RunPython(set_date_of_data_exists, migrations.RunPython.noop),
    ]
