# Generated by Django 2.2.15 on 2020-10-27 11:57

from django.db import migrations


def set_coverage_statuses(apps, schema_editor):
    SchoolWeeklyStatus = apps.get_model('connection_statistics', 'SchoolWeeklyStatus')

    sw_qs = SchoolWeeklyStatus.objects.exclude(connectivity_type='unknown')
    for sw in sw_qs:
        if sw.connectivity_type and sw.connectivity_type.lower() != 'unknown':
            sw.coverage_availability = True
            if sw.connectivity_type.lower() in ['2g', '3g', '4g']:
                sw.coverage_type = sw.connectivity_type.lower()

        if sw.connectivity_type and sw.connectivity_type.lower() in ['no covered', 'no', 'no service']:
            sw.coverage_type = 'no'
            sw.coverage_availability = False

        sw.save()


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0031_auto_20201027_1150'),
    ]

    operations = [
        migrations.RunPython(set_coverage_statuses, migrations.RunPython.noop),
    ]
