# Generated by Django 2.2.15 on 2020-11-30 08:07

from django.db import migrations, models


def set_default_country_status(apps, schema_editor):
    Country = apps.get_model('locations', 'Country')

    for country in Country.objects.all():
        if country.last_weekly_status:
            if country.last_weekly_status.integration_status == 0:
                country.last_weekly_status.integration_status = 4
                country.last_weekly_status.save(update_fields=('integration_status',))


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0039_auto_20201120_1411'),
        ('locations', '0010_auto_20201120_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='integration_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Country Joined Project Connect'), (1, 'School locations mapped'), (2, 'Static connectivity mapped'), (3, 'Real time connectivity mapped'), (4, 'Default Country Status'), (5, 'School OSM locations mapped')], default=4),
        ),
        migrations.RunPython(set_default_country_status, migrations.RunPython.noop)
    ]
