version: 2
jobs:
  test:
    machine: true
    docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Run Tests
          command: docker-compose -f docker/docker-compose.test.yml up --build --abort-on-container-exit

  build_and_upload:
    docker_layer_caching: true
    machine: true
    steps:
      - checkout
      - run:
          name: Building the image
          command: docker build -f docker/Dockerfile . -t rttest/project-connect-api:prod
      - run:
          name: Pushing to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push rttest/project-connect-api:prod
      - run:
          name: trigger redeploy
          command: |
            curl example.com

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build_and_upload:
          requires:
            - test
          filters:
            branches:
              only:
                - master
