version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}--{{ checksum "requirements/common.txt" }}--{{ checksum "requirements/dev.txt" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Run Tests
          command: docker-compose -f docker/docker-compose.test.yml up --build --abort-on-container-exit
      - save_cache:
          key: deps2-{{ .Branch }}--{{ checksum "requirements/common.txt" }}--{{ checksum "requirements/dev.txt" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - /root/.cache/pip

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
