version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: proco-backend-image-{{ checksum "docker/Dockerfile" }}
      - run:
          name: Load image if available
          command: /bin/bash -c "[ -f /tmp/backend.image ] && docker load -i /tmp/backend.image || true"
      - run:
          name: Run Tests
          command: docker-compose -f docker/docker-compose.test.yml up --build --abort-on-container-exit
      - run:
          name: Save image
          command: docker save rttest/project-connect-api:prod -o /tmp/backend.image
      - save_cache:
          key: proco-backend-image-{{ checksum "docker/Dockerfile" }}
          force: yes
          paths:
            - /tmp/backend.image

  build_and_upload:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: proco-backend-image-{{ checksum "docker/Dockerfile" }}
      - run:
          name: Load built image
          command: docker load -i /tmp/backend.image
      - run:
          name: Building the image
          command: docker build -f docker/Dockerfile . -t rttest/project-connect-api:prod
      - run:
          name: Pushing to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push rttest/project-connect-api:prod
      - run:
          name: trigger redeploy
          command: |
            curl ${DEPLOY_URL}?key=${DEPLOY_API_KEY}

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build_and_upload:
          requires:
            - test
          filters:
            branches:
              only:
                - master
