# Generated by Django 2.2.15 on 2020-11-30 09:08

from django.db import migrations


def set_not_verified_statuses(apps, schema_editor):
    Country = apps.get_model('locations', 'Country')

    for country in Country.objects.filter(data_source__icontains='osm'):
        country.last_weekly_status.integration_status = 5
        country.last_weekly_status.save(update_fields=('integration_status',))


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20201120_1407'),
    ]

    operations = [
        migrations.RunPython(set_not_verified_statuses, migrations.RunPython.noop)
    ]
