version: '3'

services:
  db:
    container_name: proco_test_db
    image: mdillon/postgis
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

  backend:
    container_name: proco_test_backend
    image: proco_backend
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: bash -c "sleep 10 && /code/scripts/wait-for-it.sh db:5432 && pipenv run /code/scripts/runtests.sh"
    environment:
      DATABASE_URL: postgres://test:test@db/test
      DJANGO_SETTINGS_MODULE: config.settings.dev
    depends_on:
      - db
