# Generated by Django 2.2.17 on 2020-12-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='organisation',
            new_name='organization',
        ),
    ]
