name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -f docker/Dockerfile . -t rttest/project-connect-api:prod

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: docker-compose -f docker/docker-compose.test.yml up --build --abort-on-container-exit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          docker push rttest/project-connect-api:prod

      - name: Trigger redeploy
        run: curl ${{ secrets.DEPLOY_URL }}?key=${{ secrets.DEPLOY_API_KEY }}
